In [1]:
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np
dataset=sns.load_dataset('tips')
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)
d_t=pd.crosstab(dataset['sex'],dataset['day'])
print(d_t)

smoker  Yes  No
sex            
Male     60  97
Female   33  54
day     Thur  Fri  Sat  Sun
sex                        
Male      30   10   59   58
Female    32    9   28   18


In [4]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [7]:
observed_values=dataset_table.values
print("observed values:-\n",observed_values)

observed values:-
 [[60 97]
 [33 54]]


In [8]:
val=stats.chi2_contingency(dataset_table)
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [9]:
exp_val=val[3]
exp_val

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [14]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_rows=len(dataset_table.iloc[0:100,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05
no_of_rows
no_rows

Degree of Freedom:- 1


2

In [15]:
no_rows

2

In [20]:
from scipy.stats import chi2
chi_sq=sum([(o-e)**2/e for o,e in zip(observed_values,exp_val)])
chi_square_statistic=chi_sq[0]+chi_sq[1]


In [21]:
print('chi-square statistic:',chi_sq)

chi-square statistic: [0.00119737 0.00073745]


In [24]:
cri_val=chi2.ppf(q=1-alpha,df=ddof)
print("cri_val",cri_val)

cri_val 3.841458820694124


In [29]:
p=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print("p value:",p)
print("significance value:",alpha)
print("degree of freedom",ddof)

p value: 0.964915107315732
significance value: 0.05
degree of freedom 1


In [30]:
if chi_square_statistic>=cri_val:
    print("reject ho,there is no relationhip between 2 cat")
else:
    print("retain ho,there is  relationhip between 2 cat")

retain ho,there is  relationhip between 2 cat


In [31]:
if p <= alpha:
    print("reject ho,there is no relationhip between 2 cat")
else:
    print("retain ho,there is relationhip between 2 cat")

retain ho,there is relationhip between 2 cat


In [32]:
#test

In [34]:
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [35]:
len(ages)

32

In [37]:
ages_mean=np.mean(ages)
print("mean of ages:",ages_mean)

mean of ages: 30.34375


In [38]:
sampsize=10
age_samp=np.random.choice(ages,sampsize)
age_samp

array([10, 18, 26, 43, 21, 35, 10, 21, 35, 43])

In [40]:
from scipy.stats import ttest_1samp
ttest,p_val=ttest_1samp(age_samp,30)
print(p_val)
print(ttest)

0.3547848614169473
-0.9755355430644616


In [42]:
import math
np.random.seed(6)
school=stats.poisson.rvs(loc=18,mu=35,size=1500)
clas=stats.poisson.rvs(loc=18,mu=30,size=60)
school.mean()
clas.mean()

46.9

In [44]:
_,pval=stats.ttest_1samp(a=clas,popmean=school.mean())
pval

1.139027071016194e-13